name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code checkout from github"
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build image
        run: echo "build docker image"
        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run testcases
        run: echo "Testing done"
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy changes
        run: echo "Deploy done"
