name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Please select option for deployment"
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
      

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code checkout from github"
        
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build image
        run: echo "build docker image"
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: run testcases
        run: echo "Testing done"
        
  deploy:
    if: inputs.environment == 'dev'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy changes
        run: echo "Deploy done"
